### ISSUE TITLE
Unable to find stinger_transition.effect which is causing OBS to crash and plugin to function

### ISSUE THREAD

**Issue by EliasRanz** [WarmUpTill/Video-Transition#7]
Getting an issue when adding the plugin to OBS on Windows 10 using v19.0.2 of OBS. I have the files in `c:\program files (x86)\obs-studio` per the [documentation](https://obsproject.com/forum/resources/video-transition-stinger-transition.498/). The stinger transition shows up in the list, but when I try to add it, it claims there are no properties found. I look in the OBS log file and it was reporting `Could not find stinger_transition.effect`.

Crash report was showing:
```
Unhandled exception: c0000005
Date/Time: 2017-05-27, 16:39:22
Fault address: 7FFDA0391FB4 (c:\program files (x86)\obs-studio\obs-plugins\64bit\stinger-transition.dll)
libobs version: 19.0.2
Windows version: 10.0 build 14393 (revision: 1198; 64-bit)
CPU: AMD Phenom(tm) II X6 1100T Processor
```
OBS UI was showing:
![image](https://user-images.githubusercontent.com/1493142/27264250-70383c54-5448-11e7-8e82-e182ebc75e7f.png)

**Comment by vknecht** [comment]
Hitting the same issue with only these messages :
> error: Could not find stinger_transition.effect
> error: Failed to create source 'StingerTransition'!

That's on Fedora 26 using [RPMFusion obs-studio package](https://admin.rpmfusion.org/pkgdb/package/free/obs-studio/), having built the plugin after some source and CMakeLists.txt tweaking, and partial OBS build from source for libff dependency which is not provided by the obs-studio-devel package.

The plugin (.so file) is detected and loaded, be it from package's system directories or from
~/.config/obs-studio/plugins/stinger-transition/bin/64bit/
but tried a lot and can't find where to put the _stinger_transition.effect_ file.

Using _strace_ doesn't show any attempt to load this file :-(

**Comment by WarmUpTill** [comment]
Sorry I'm not really familiar with the file structure of OBS Studio in other versions besides the windows one.
The windows version of OBS has separate data folders for all the different modules being used by OBS. So for the stinger transition plugin the stinger_transition.effect file should be located in 
"\<your install path\>\obs-studio\data\obs-plugins\stinger-transition". I hope this helps clear things up.

As a side note, the next version of OBS will have built in support for the stinger transitions, which will be a lot more stable and will perform better (and will not require the user to manually install a plugin of course). This new version (created by Jim?) relies on some new function calls that allows transitions to render video files directly ( instead of creating textures of the video frames and entering them in the buffer of the currently not visible scene). So I cant just release that better version in the forum thread of the plugin (besides it not being written by me in the first place).

**Comment by EliasRanz** [comment]
@WarmUpTill So basically the direction to go is wait for the next version of OBS Studio, which should natively support video transitions?
